baseURL: /
# TODO: Remove theme and move without it
theme: "anatole"
googleAnalytics: "UA-72740909-2"
pygmentsUseClasses: true
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
enableEmoji: true
enableRobotsTXT: true

params:
  title: "Asil Barkın Elik"
  author: "Asil Barkın Elik"
  copyright: "1991-2021"
  description: curious and passionate polyglot programmer
  profilePicture: "images/profile.jpg"
  favicon: "favicons/"
  mainSections: []
  singleDateFormat: "02 Jan 15:04"
  indexDateFormat: "02 Jan 15:04"
  listDateFormat: "02 Jan 15:04"
  postSectionName: "posts"
  doNotLoadAnimations: true
  enableMediumZoom: false
  customCss: ['override-theme.css']

  socialIcons:
    - icon: "fab fa-linkedin"
      title: "Linkedin"
      url: "https://www.linkedin.com/in/asilelik"
    - icon: "fab fa-github"
      title: "GitHub"
      url: "https://github.com/asilelik"
    - icon: "fab fa-twitter"
      title: "Twitter"
      url: "https://twitter.com/asilelik"
    - icon: "fas fa-download"
      title: "CV"
      url: "/files/Asil_Barkin_Elik_CV.pdf"
    - icon: "fas fa-envelope"
      title: "e-mail"
      url: "mailto:asilelik@gmail.com"

markup:
  goldmark:
    renderer:
      unsafe: true # Used for anchors and cites

menu:
  main:
    - name: "Home"
      weight: 100
      url: "/"
    - name: "Blog"
      weight: 200
      url: "/posts/"
    - name: "About Me"
      weight: 300
      url: "/about/"
