baseURL: /
theme: "anatole"
languageCode: "en"
DefaultContentLanguage: "en"
googleAnalytics: "UA-72740909-2"
pygmentsUseClasses: true
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
summarylength: 10
enableEmoji: true
enableRobotsTXT: true
params:
  title: ""
  author: "Asil BarkÄ±n Elik"
  copyright: "1991-2021"
  description: curious and passionate polyglot programmer
  profilePicture: "images/profile.jpg"
  keywords: ""
  favicon: "favicons/"
  # example ["css/custom.css"]
  customCss: []
  # example ["js/custom.js"]
  customJs: [] 
  # If you prefer having a static page as your home page rather than a listing of the latest posts, then make sure you leave the mainSections parameter blank
  # [params]
  #   mainSections: []
  #   Put any content into the _index.md file located in the content directory. If you want, you can also have some static text and the posts below. In such case, simply keep the mainSections: ["post"] and put any static content in the _index.md.
  mainSections: []
  # images: ["images/site-feature-image.png"]
  singleDateFormat: "02 Jan 15:04"
  indexDateFormat: "02 Jan 15:04"
  listDateFormat: "02 Jan 15:04"
  # Read More links for truncated summaries
  # readMore: true
  # Rename post section
  postSectionName: "Blog"
  displayMode: "dark"
  disableThemeSwitcher: false # Theme switcher is enabled by default
  doNotLoadAnimations: true # Animations are loaded by default
  # for google analytics v4
  # gtagId: "G-XXXXXXXXXX"
  enableMediumZoom: false

  socialIcons:
    - icon: "fab fa-linkedin"
      title: "Linkedin"
      url: "https://www.linkedin.com/in/asilelik"
    - icon: "fab fa-github"
      title: "GitHub"
      url: "https://github.com/asilelik"
    - icon: "fab fa-twitter"
      title: "Twitter"
      url: "https://twitter.com/asilelik"
    - icon: "fas fa-download"
      title: "CV"
      url: "https://asil.dev/files/cv.pdf"
    - icon: "fas fa-envelope"
      title: "e-mail"
      url: "mailto:asilelik@gmail.com"
markup:
  goldmark:
    renderer:
      unsafe: true
menu:
  main:
    - name: "Home"
      identifier: "home"
      weight: 100
      url: "/"
    - name: "Blog"
      weight: 200
      identifier: "posts"
      url: "/posts/"
    - name: "About"
      weight: 300
      identifier: "about"
      url: "/about/"
